name: 'Documentation Spell Check'
description: 'Checks spelling in documentation'
inputs:
  working-directory:
    description: 'Working directory'
    required: true
    default: '.'
runs:
  using: 'composite'
  steps:
    - run: python3 $GITHUB_ACTION_PATH/spellcheck.py ${{ inputs.working-directory }}
      shell: bash