name: 'Inclusive Language Check'
description: 'Checks for inclusive language in documentation'
inputs:
  working-directory:
    description: 'Working directory'
    required: true
    default: '.'
runs:
  using: 'composite'
  steps:
    - run: python3 ./inclusive_language.py ${{ inputs.working-directory }}
      shell: bash