name: 'Link Check'
description: 'Checks links in documentation'
inputs:
  working-directory:
    description: 'Working directory'
    required: true
    default: '.'
runs:
  using: 'composite'
  steps:
    - run: python3 ./linkcheck.py ${{ inputs.working-directory }}
      shell: bash