name: 'Accessibility check'
description: 'Runs pa11y against the documentation'
inputs:
  working-directory:
    description: 'Working directory'
    required: true
    default: '.'
  makefile:
    description: 'Name of the Makefile to use (default: "Makefile.sp" if it exists, "Makefile" otherwise)'
    required: false
    type: string
    default: 'use-default'
  install-target:
    description: 'Target to run to install the tools (default: "install")'
    required: false
    type: string
    default: 'install'
  pa11y-target:
    description: 'Target to run for the accessibility check (default: "pa11y")'
    required: false
    type: string
    default: 'pa11y'
runs:
  using: 'composite'
  steps:
    - run: python3 $GITHUB_ACTION_PATH/pa11y.py ${{ inputs.working-directory }} --install_target ${{ inputs.install-target }} --pa11y_target ${{ inputs.pa11y-target }} --makefile ${{ inputs.makefile }}
      shell: bash
